FROM debian:12-slim

# build-environment for ebpf modules (without using ebpf-go)

# INIT: docker build -t ebpf-compiler .
# BUILD BINARY:
#   docker run --rm -v "$(pwd)":/repo ebpf-compiler clang -O2 -target bpf -c /repo/ebpf_mod1.c -o /app/ebpf_mod1.o

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    llvm \
    libelf-dev \
    zlib1g-dev \
    libbpf-dev \
    bpftool \
    linux-headers-generic && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /repo

